name: Product PR Validation

on:
  pull_request:
    branches:
      - develop
    types:
        ### runs when a new PR is created, e.g. feature/login-fix → develop###
      - opened
        ### runs again whenever you push new commits to that feature branch while the PR is still open.
      - synchronize
        ### runs if someone closes the PR without merging and later reopens it.
      - reopened

permissions:
  contents: read

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m pytest tests/unit -v


  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API Tests
        run: |
          python -m pytest tests/api -v


      # We'll add these later
      # - Coverage
      # - SonarQube
      # - Trivy filesystem scan